; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[base][download][type] = ""
projects[base][download][url] = ""
projects[base][type] = "module"

projects[views_bulk_operations][version] = "3.0-rc1"

projects[admin][version] = "2.0-beta3"

projects[admin_menu][version] = "3.0-rc3"

projects[backup_migrate][version] = "2.3"

projects[backup_migrate_files][version] = "1.x-dev"

projects[ctools][version] = "1.0"

projects[chart][version] = "1.1"

projects[clientside_validation][version] = "1.31"

projects[date][version] = "2.5"

projects[devel][version] = "1.2"

projects[ds][version] = "1.5"

projects[email][version] = "1.0"

projects[entity][version] = "1.0-rc3"

projects[extlink][version] = "1.12"

projects[field_group][version] = "1.1"

projects[file_entity][version] = "2.0-unstable5"

projects[filefield_sources][version] = "1.4"

projects[fpa][version] = "2.2"

projects[globalredirect][version] = "1.4"

projects[google_analytics_reports][version] = "3.x-dev"

projects[google_analytics][version] = "1.2"

projects[hierarchical_select][version] = "3.0-alpha5"

projects[image_resize_filter][version] = "1.13"

projects[imce][version] = "1.5"

projects[imce_filefield][version] = "1.x-dev"

projects[imce_mkdir][version] = "1.0"

projects[imce_rename][version] = "1.2"

projects[imce_wysiwyg][version] = "1.0"

projects[insert][version] = "1.1"

projects[libraries][version] = "1.0"

projects[linkit][version] = "2.5"

projects[menu_block][version] = "2.3"

projects[metatag][version] = "1.0-alpha6"

projects[module_filter][version] = "1.6"

projects[mollom][version] = "1.1"

projects[nodeformcols][version] = "1.x-dev"

projects[oauth][version] = "3.0"

projects[panels][version] = "3.2"

projects[pathauto][version] = "1.1"

projects[pathologic][version] = "1.4"

projects[profiler_builder][version] = "1.0-alpha2"

projects[rules][version] = "2.1"

projects[semanticviews][version] = "1.x-dev"

projects[site_verify][version] = "1.0"

projects[spamspan][version] = "1.1-beta1"

projects[taxonomy_manager][version] = "1.0-beta2"

projects[taxonomy_menu][version] = "1.2"

projects[token][version] = "1.1"

projects[total_control][version] = "2.3-beta1"

projects[views][version] = "3.3"

projects[views_slideshow][version] = "3.0"

projects[webform][version] = "3.18"

projects[wysiwyg][version] = "2.1"

; Themes
projects[om][version] = "2.21"

projects[om_admin][version] = "2.2"

projects[rubik][version] = "4.0-beta8"

projects[tao][version] = "3.0-beta4"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.3/ckeditor_3.6.3.tar.gz"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = "https://github.com/mehrpadin/Superfish-for-Drupal/tarball/master"
libraries[superfish][download][url] = "get"
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[profiler][download][type] = "get"
libraries[profiler][download][url] = "http://ftp.drupal.org/files/projects/profiler-7.x-2.0-beta1.tar.gz"
libraries[profiler][directory_name] = "profiler"
libraries[profiler][type] = "library"

